<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ForOverReferralsLib\Models;

/**
 * The force bonuses' form
 */
class BonusForm
{
    /**
     * The bonuses' wrapper
     * @required
     * @var Bonus $bonus public property
     */
    public $bonus;

    /**
     * Constructor to set initial or default values of member properties
     * @param Bonus $bonus Initialization value for $this->bonus
     */
    public function __construct(Bonus $bonus)
    {
        $this->bonus = $bonus;
    }


    public function toArray(): array
    {
        return $this->bonus->toArray();
    }
}
