<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ForOverReferralsLib\Models;

/**
 * The redemption request's form
 */
class RedemptionForm
{
    /**
     * The redemption request's wrapper
     * @required
     * @maps redemption_request
     * @var Redemption $redemption public property
     */
    public $redemption;

    /**
     * Constructor to set initial or default values of member properties
     * @param Redemption $redemption Initialization value for $this->redemption
     */
    public function __construct(Redemption $redemption)
    {
        $this->redemption = $redemption;
    }


    /**
     * Encode this object to JSON
     */
    public function toArray(): array
    {
        return $this->redemption->toArray();
    }
}
