<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ForOverReferralsLib\Models;

/**
 * Redemption Request structure
 */
class Redemption
{
    /**
     * The advocate's token
     * @required
     * @maps advocate_token
     * @var string $advocate_token public property
     */
    public $advocate_token;

    /**
     * The request status identifier
     * @required
     * @maps request_status_slug
     * @var string $status public property
     */
    public $status;

    /**
     * The request action identifier
     * @required
     * @maps request_action_slug
     * @var string $action_slug public property
     */
    public $action_slug;

    /**
     * The amount to be redeemed
     * @required
     * @var integer $amount public property
     */
    public $amount;

    /**
     * The description of the requests, useful to store extra information about the request.
     * @var string $description public property
     */
    public $description;

    public function __construct($advocate_token, $status, $action_slug, $amount, $description)
    {
        $this->advocate_token = $advocate_token;
        $this->status = $status;
        $this->action_slug = $action_slug;
        $this->amount = $amount;
        $this->description = $description;
    }


    public function toArray(): array
    {
        return [
            'advocate_token' => $this->advocate_token,
            'status' => $this->status,
            'action_slug' => $this->action_slug,
            'amount' => $this->amount,
            'description' => $this->description,
        ];
    }
}
