<?php
/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ForOverReferralsLib\Models;

/**
 * The referral's form
 */
class ReferralForm
{
    /**
     * The referral's wrapper
     * @required
     * @var Referral $referral public property
     */
    public $referral;

    /**
     * Constructor to set initial or default values of member properties
     * @param Referral $referral Initialization value for $this->referral
     */
    public function __construct(Referral $referral)
    {
        $this->referral = $referral;
    }

    public function toArray(): array
    {
        return $this->referral->toArray();
    }
}
